Traceback (most recent call last):
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import umap.plot
------------------

----- stderr -----
/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/umap/plot.py:20: UserWarning: The umap.plot package requires extra plotting libraries to be installed.
    You can install these via pip using

    pip install umap-learn[plot]

    or via conda using

     conda install pandas matplotlib datashader bokeh holoviews colorcet scikit-image
    
  warn(
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[30], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mumap[39;00m[38;5;21;01m.[39;00m[38;5;21;01mplot[39;00m

File [0;32m~/miniforge3/envs/octave/lib/python3.11/site-packages/umap/plot.py:31[0m
[1;32m     19[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[1;32m     20[0m     warn(
[1;32m     21[0m [38;5;250m        [39m[38;5;124;03m"""The umap.plot package requires extra plotting libraries to be installed.[39;00m
[1;32m     22[0m [38;5;124;03m    You can install these via pip using[39;00m
[0;32m   (...)[0m
[1;32m     29[0m [38;5;124;03m    """[39;00m
[1;32m     30[0m     )
[0;32m---> 31[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(
[1;32m     32[0m         [38;5;124m"[39m[38;5;124mumap.plot requires pandas matplotlib datashader bokeh holoviews scikit-image and colorcet to be [39m[38;5;124m"[39m
[1;32m     33[0m         [38;5;124m"[39m[38;5;124minstalled[39m[38;5;124m"[39m
[1;32m     34[0m     ) [38;5;28;01mfrom[39;00m [38;5;28;01mNone[39;00m
[1;32m     36[0m [38;5;28;01mimport[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdecomposition[39;00m
[1;32m     37[0m [38;5;28;01mimport[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcluster[39;00m

[0;31mImportError[0m: umap.plot requires pandas matplotlib datashader bokeh holoviews scikit-image and colorcet to be installed

